include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_specify_types: true
    always_put_required_named_parameters_first: true
    always_put_control_body_on_new_line: true
    prefer_single_quotes: true
    require_trailing_commas: true
    discarded_futures: true
    unnecessary_to_list_in_spreads: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    non_constant_identifier_names: false
