name: Pull request

on:
  pull_request:

jobs:
  format_and_analyze:
    name: Format and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get
        run: flutter pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze

  # Make a job with the title of pull request contains "flutter_native_splash" and only on opened pull request
  native_splash:
    if: contains(github.event.pull_request.title, 'flutter_native_splash') && (github.event.action == 'opened' || github.event.action == 'synchronize')
    needs:
      - format_and_analyze
    name: Flutter Native Splash
    runs-on: ubuntu-latest

    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get
        run: flutter pub get

      - name: Flutter Native Splash
        run: flutter pub run flutter_native_splash:create

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update native splash'
