name: Pull request

on:
  pull_request:

jobs:
  format_and_analyze:
    name: Format and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get
        run: flutter pub get

      - name: Test
        run: flutter test -v

  # Make a job with the title of pull request contains "flutter_native_splash" and only on opened pull request
  native_splash:
    if: contains(github.event.pull_request.title, 'flutter_native_splash') && github.event.action == 'opened'
    needs:
      - format_and_analyze
      - test
    name: Flutter Native Splash
    runs-on: ubuntu-latest

    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get
        run: flutter pub get

      - name: Flutter Native Splash
        run: flutter pub run flutter_native_splash:create

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "flutter_native_splash" || exit 0
          git push origin ${{ steps.extract_branch.outputs.branch }}